# Generated by Django 4.2.3 on 2023-07-05 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateTimeField(verbose_name='Data de Retirada')),
                ('drop_off_date', models.DateTimeField(verbose_name='Data de Entrega')),
                ('observations', models.TextField(blank=True, max_length=100, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='cars.car', verbose_name='Carro')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Aluguéis',
                'ordering': ['car', '-pick_up_date', 'drop_off_date'],
            },
        ),
    ]
