# Generated by Django 4.2.3 on 2023-07-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_rental_options_rename_car_rental_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['car', '-pick_up_date', 'drop_off_date'], 'verbose_name': 'Aluguel', 'verbose_name_plural': 'Aluguéis'},
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='vehicle',
            new_name='car',
        ),
    ]
