# Generated by Django 4.2.3 on 2023-07-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_rental_options_rename_vehicle_rental_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Aprovada'), (2, 'Cancelada')], default=0, verbose_name='Situação'),
        ),
    ]
