databases:
  - name: car_rental
    databaseName: car_rental
    user: car_rental

services:
  - type: web
    name: car_rental
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn car_rental.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: car_rental
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4