# Generated by Django 4.2.3 on 2023-07-05 17:43

import car_rental.cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('plate', models.CharField(max_length=7, verbose_name='Placa')),
                ('year', car_rental.cars.models.YearField(verbose_name='Ano')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Alugado'), (1, 'Disponível'), (2, 'Manutenção')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['model'],
            },
        ),
    ]
