# Generated by Django 4.2.3 on 2023-07-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_rental_options_rename_car_rental_vehicle'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Vehicle',
        ),
    ]
