# Generated by Django 4.2.3 on 2023-07-20 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message="A placa do veículo precisa estar nos formatos:         'AAA0A00' ou 'AAA0000'", regex='^[A-Z]{3}[0-9][0-9A-Z][0-9]{2}$')], verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disponível'), (2, 'Manutenção')], default=1, verbose_name='Situação'),
        ),
    ]
